version: "3.7"
services:
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Master99
  web:
    image: "php:8.2-apache"
    container_name: php-container
    restart: always
    volumes:
      - ./usercontrol:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - db
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    working_dir: /app
    restart: always
    volumes:
      - ./usercontrol:/app
    depends_on:
       - db
    env_file:
      - usercontrol/.env.example
      - usercontrol/.env